version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: CRUD_With_Cash_Postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  #TODO Connect to our server about when we start the pgadmin container
  pgadmin:
    image: dpage/pgadmin4
    container_name: CRUD_With_Cash_PgAdmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

  redis:
    image: redis:7
    container_name: CRUD_With_Cash_Redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
